### ISSUE TITLE
Too much of the feather colour in this image, please adjust the colour configuration 

### ISSUE THREAD

**Issue by marcaltorroella** [Ivanobix/ToxicFishing#2]
I always get spammed with the "Too much of the feather colour in this image, please adjust the colour configuration !" message. How I am suposed to calibrate the red color for the feather in this version?

**Comment by Ivanobix** [comment]
@marcaltorroella 
I apologize for the unclear error description; that was my oversight. The error message suggests that there's an excessive amount of red (or colors resembling red like orange) at the center of your screen. To address this, please select a fishing area devoid of red hues. It's best to zoom in using the mouse wheel until only the water and fishing bait are in view.

This approach is implemented because the algorithm identifies the fishing bait via the red feather, thereby negating the need for other detection methods, such as DLL injection.

That said, I truly appreciate your feedback and will incorporate a clearer description in the next version of the software.

**Comment by marcaltorroella** [comment]
I deduced that that was what it was about, but even if I zoomed in so that only the water and the bait were visible, the same message still appeared. I even tried with alt+z to hide the UI. Tried with the water from SW which is clearly blue (no red tones). I debugged the function and it's returning like 4300 points.
